// src/routes/PageListPendingItems.tsx
import { useMemo } from 'react';
import { useSelector } from 'react-redux';
import { BaseCard } from '../components/BaseCard';
import { ListItem } from '../components/ListItem';
import { type RootState } from '../stores';

export const PageListPendingItems = () => {
  const list = useSelector((state: RootState) => state.todoList.list);

  const hasItems = useMemo(() => {
    return !!list.length;
  }, [list.length]);

  return (
    <BaseCard className="col-start-5 col-span-4 row-start-2 row-span-10">
      {!hasItems && <div>No pending Items</div>}

      <ul className="flex flex-col gap-3">
        <ListItem description="Make the Todo list work" />
        <ListItem description="Make the ListItem Component" state="done" />
      </ul>
    </BaseCard>
  );
};

// src/routes/PageListPendingItems.vue
<script setup lang="ts">
import { computed } from 'vue';
import { BaseCard } from '@/components/BaseCard';
import { useTodoListStore } from '@/stores/useTodoListStore';
import { ListItem } from '@/components/ListItem';

const { list } = useTodoListStore();

const hasItems = computed(() => {
  return !!list.length;
});
</script>

<template>
  <base-card class="col-start-5 col-span-4 row-start-2 row-span-10">
    <div v-if="!hasItems">No pending Items</div>

    <ul class="flex flex-col gap-3">
      <list-item description="Make the Todo list work" />
      <list-item description="Make the ListItem Component" state="done" />
    </ul>
  </base-card>
</template>

<style scoped></style>
