// src/routes/PageListDoneItems.tsx
import { BaseCard } from '../components/BaseCard';
import { useSelector } from "react-redux";
import { type RootState } from "../stores";
import { ListItem } from "../components/ListItem";
import type { ListItem as ListItemType } from "@/types";

export const PageListDoneItems = () => {
  const { todos }= useSelector((state: RootState) => state.todoList);

  return (
    <BaseCard className="col-start-5 col-span-4 row-start-2">
      <ul className="flex flex-col gap-3">
        {todos
          .filter((todo: ListItemType) => todo.state === "done")
          .map((todo: ListItemType) => (
            <ListItem
              key={todo.id}
              description={todo.description}
              state={todo.state}
            />
          ))}
      </ul>
    </BaseCard>
  );
};

// src/routes/PageListDoneItems.vue
<script setup lang="ts">
import { computed } from 'vue';
import { BaseCard } from '@/components/BaseCard';
import { useTodoListStore } from '@/stores/useTodoListStore';
import { ListItem } from '@/components/ListItem';
import { Filter } from '@/components/Filter';

const store = useTodoListStore();

const hasItems = computed(() => {
  return !!store.completedItems.length;
});
</script>

<template>
  <base-card class="col-start-5 col-span-4 row-start-2 row-span-10">
    <Filter />
    
    <div v-if="!hasItems">No completed Items</div>

    <ul v-else class="flex flex-col gap-3">
      <list-item 
        v-for="item in store.completedItems" 
        :key="item.id"
        :id="item.id"
        :description="item.description" 
        :state="item.state"
      />
    </ul>
  </base-card>
</template>

<style scoped>

</style>
