// src/App.tsx
import { RouterProvider } from 'react-router-dom';
import { TheHeader } from './components/TheHeader';
import { router } from './routes';

function App() {
  return (
    <div className="w-screen h-screen grid cols-12 rows-12 gap-3 bg-neutral-100">
      <TheHeader />
      <RouterProvider router={router} />
    </div>
  );
}

export default App

// src/App.vue
<script setup lang="ts">
import { TheHeader } from '@/components/TheHeader';
import { Notification } from '@/components/Notification';
import { useNotificationStore } from '@/stores/useNotificationStore';

const notificationStore = useNotificationStore();
</script>

<template>
  <div class="w-screen h-screen grid grid-cols-12 grid-rows-12 gap-3 bg-neutral-100">
    <TheHeader />
    <router-view></router-view>
    <Notification 
      :message="notificationStore.message" 
      :visible="notificationStore.visible" 
      :type="notificationStore.type"
    />
  </div>
</template>

<style scoped></style>
